### ISSUE TITLE
Support for IE11, Edge?

### ISSUE THREAD

**Issue by kateika** [AlmeroSteyn/react-aria-live#4]
Hi, I didn't find where I can write you to ask about IE browsers support (+Edge) for the first version of react-aria-live (we have React 16.2). 
Because it seems that it doesn't work for IE11 (at least it works very unstable). 
In our app sometimes it doesn't announce first message, only second. Did you face something familiar?

**Comment by AlmeroSteyn** [comment]
@kateika thanks for letting me know.

Firstly, could you let me know what screen reader you are using with IE11?

What you are experiencing sounds like the live region isn't already rendered once the first update happens.

The `<LiveAnnouncer>` component needs to be rendered and stable **before** the first message is sent to the live region. Can you check and confirm that? In that case the best way to handle this is to render the `<LiveAnnouncer>` as the very first component in your application. 

Also are you perhaps using `Gatsby` in this application?

**Comment by AlmeroSteyn** [comment]
@kateika could you perhaps reproduce the issue you have in a small Github repo and send me the link? 

There should not be two sets of live regions, are you rendering the `<LiveAnnouncer>` twice? 

Also NVDA is used relatively rarely with IE or EDGE. Check out the combos from the WebAIM screen screen reader survey: https://webaim.org/projects/screenreadersurvey7/#browsercombos

Now I am not saying this is not an issue with the package, there are just reasons to believe that what you are experiencing is either related to how you are using it, or a browser/screen reader integration issue.

Would it also be possible for you to test your application using the JAWS screen reader? This is mostly used in combination with IE.

**Comment by kateika** [comment]
@AlmeroSteyn we know about poor IE/Edge+NVDA compatibility but client decided to have it at least for now. Also, we don't have JAWS unfortunately.

As I was doing a Github repo with an example, it appears we face an issue for every browser + NVDA (Chrome, Firefox, IE). And this issue is connected with announce of the same error. In your library description on npm you advise to push empty string if we need to announce the same text. Unfortunately if we do it quickly screen reader doesn't understand changes, especially slow is IE. The only option which we found is to use setTimeout. You can try this in this repo https://github.com/kateika/react-aria-live-clean-msg 

P.S. I am not sure if found issues is somehow connected with created one. We probably should close this with note that it's supported IE11 and create another one, please advise.

**Comment by AlmeroSteyn** [comment]
@kateika thanks for updating. Unfortunately browser/screen reader integration is outside the scope of this library. Please log an issue with NVDA itself for that. I would once again advise to test IE pages with JAWS. Edge has a number of integration issues even with JAWS. Once again, these will need to be fixed by the teams building the various browsers and screen readers. 

As for clearing the live region. I am aware of this and `v2` of this library adds extensive functionality to make this easier and more certain. Please make use of `v2`. If you React version stops you from upgrading to `v2` the only way to ensure this would indeed be with a `setTimeout` as you mentioned.

In the light of this I am closing this issue.
